#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ "$#" != 0 && ${1:-} != "--validate-only" ]]; then
    echo 'Splits the shard into two children shards.'
    echo
    echo 'Usage: split-shard'
    echo '       split-shard --validate-only'
    exit 2
fi

for dependency in sed kustomize yq envsubst
do
    if ! which "$dependency" &> /dev/null; then
        echo
        echo "ERROR: $dependency is not installed on your system."
        echo
        exit 2
    fi
done

function find_script_dir {
    SOURCE=${BASH_SOURCE[0]}
    while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is not a symlink
        DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
        SOURCE=$(readlink "$SOURCE")
        # If $SOURCE was a relative symlink, we need to resolve it relative
        # to the path where the symlink file was located.
        [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
    done
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    export SWPT_SHARD_DIR="$DIR"
}

function yq_ensure {
    result=$(yq "... comments=\"\" | $2" "$1")
    if [[ "$result" != "$3" ]]; then
        echo
        echo "ERROR: Unexpected value for '$2' in $1."
        echo
        echo "Expected '$3', got '$result'."
        exit 1
    fi
}

function validate_shard_kustomization_file {
    fname="$DIR/kustomization.yaml"
    echo "Validating ${fname}:"

    echo '... Ensuring required fields are present.'
    yq_ensure "$fname" '.apiVersion' kustomize.config.k8s.io/v1beta1
    yq_ensure "$fname" '.kind' Kustomization
    yq_ensure "$fname" '.labels | kind' seq
    yq_ensure "$fname" '.configMapGenerator | kind' seq
    yq_ensure "$fname" '.secretGenerator | kind' seq
    yq_ensure "$fname" '.replicas | kind' seq
    yq_ensure "$fname" '.resources | kind' seq
    yq_ensure "$fname" '.patches | kind' seq
    yq_ensure "$fname" '.replacements | kind' seq

    echo '... Ensuring no common namespace is declared.'
    yq_ensure "$fname" '. | has("namespace")' false

    echo '... Ensuring no namePrefix is declared.'
    yq_ensure "$fname" '. | has("namePrefix")' false

    echo '... Ensuring the correct nameSuffix is declared.'
    yq_ensure "$fname" '.nameSuffix' "$SHARD_SUFFIX"

    echo '... Ensuring common labels are correctly declared.'
    yq_ensure "$fname" '.labels | length' 1
    yq_ensure "$fname" '.labels[0] | kind' map
    yq_ensure "$fname" '.labels[0] | length' 2
    yq_ensure "$fname" '.labels[0].includeSelectors' true
    yq_ensure "$fname" '.labels[0].pairs | kind' map
    yq_ensure "$fname" '.labels[0].pairs | length' 1
    yq_ensure "$fname" '.labels[0].pairs."app.kubernetes.io/instance"' "$SHARD_BASENAME"

    echo '... Ensuring base resources are included.'
    yq_ensure "$fname" ".resources[] | select(. == \"${BASE_DIR}\")" "$BASE_DIR"

    echo "... Ensuring shard's configuration contains the correct routing key."
    literals='.configMapGenerator[] | select(.name == "shardconfig") .literals'
    varname='PROTOCOL_BROKER_QUEUE_ROUTING_KEY'
    yq_ensure "$fname" "${literals} | kind" seq
    yq_ensure "$fname" "${literals}[] | select(. == \"${varname}=*\")" "${varname}=${SHARD_ROUTING_KEY}"

    echo '... Ensuring "http-cache-nginx-config" configmap is correctly declared.'
    files='.configMapGenerator[] | select(.name == "http-cache-nginx-config") .files'
    yq_ensure "$fname" "${files} | kind" seq
    yq_ensure "$fname" "${files}[] | select(. == \"nginx.conf=*\") | kind" scalar
    yq_ensure "$fname" "${files}[] | select(. == \"default.conf.template=*\") | kind" scalar

    echo '... Ensuring PostgreSQL secrets are correctly declared.'
    for db_user in postgres standby db-owner
    do
        config_name_suffix='cluster-name.credentials.postgresql.acid.zalan.do'
        password_file='../../secrets/postgres-cluster-password.encrypted'
        db_user_underscored="$(echo $db_user | sed 's/-/_/')"
        yq_ensure "$fname"\
                  ".secretGenerator[] | select(.name == \"${db_user}.${config_name_suffix}\" and .type == \"Opaque\" and .options.disableNameSuffixHash == true and .options.labels.application == \"spilo\" and .options.labels.team == \"swpt\" and .options.labels.cluster-name == \"cluster-name\" and .literals[0] == \"username=${db_user_underscored}\" and .files[0] == \"password=${password_file}\") | kind"\
                  map
    done

    echo '... Ensuring the "postgres-cluster.yaml" patch is applied.'
    patches_dir="${BASE_DIR}patches/"
    yq_ensure "$fname"\
              ".patches[] | select(.path == \"${patches_dir}postgres-cluster.yaml\" and .target.group == \"acid.zalan.do\" and .target.kind == \"postgresql\" and .target.name == \"db\" and .target.version == \"v1\") | kind"\
              map

    echo '... Ensuring critical replacements are applied.'
    replacements_dir="${BASE_DIR}replacements/"
    for filename in \
            http-cache-size\
            secrets-clustername\
            secrets-namesuffix\
            shardconfig\
            walg-exporter-image\
            webserver
    do
        yq_ensure "$fname"\
                  ".replacements[] | select(.path == \"${replacements_dir}${filename}.yaml\") | kind"\
                  map
    done

    echo '... Ensuring the "clone" replacements are not applied.'
    yq_ensure "$fname"\
              ".replacements[] | select(.path == \"${replacements_dir}clone-clustername.yaml\" or .path == \"${replacements_dir}clone-timestamp.yaml\") | kind"\
              ""

    echo '... Ensuring the number replicas is declared for each deployment.'
    for replica_name in \
            web-server\
            messages-flusher\
            messages-consumer\
            chores-consumer\
            http-cache
    do
        yq_ensure "$fname" ".replicas[] | select(.name == \"${replica_name}\") | has(\"count\")" true
    done
}

function validate_shard_postgres_cluster {
    fname="$DIR/postgres-cluster.yaml"
    echo "Validating ${fname}:"

    echo '... Ensuring required fields are present.'
    yq_ensure "$fname" '.apiVersion' acid.zalan.do/v1
    yq_ensure "$fname" '.kind' postgresql
    yq_ensure "$fname" '.metadata | kind' map
    yq_ensure "$fname" '.spec | kind' map
    yq_ensure "$fname" '.spec | has("dockerImage")' true
    yq_ensure "$fname" '.spec | has("numberOfInstances")' true
    yq_ensure "$fname" '.spec.volume | kind' map
    yq_ensure "$fname" '.spec.volume | has("size")' true
    yq_ensure "$fname" '.spec.postgresql | kind' map
    yq_ensure "$fname" '.spec.postgresql | has("version")' true

    echo '... Ensuring correct cluster name.'
    yq_ensure "$fname" '.metadata.name' db

    echo '... Ensuring no "standby:" or "clone:" sections are declared.'
    yq_ensure "$fname" '.spec | has("standby")' false
    yq_ensure "$fname" '.spec | has("clone")' false

    echo '... Ensuring an "env:" section is declared.'
    yq_ensure "$fname" '.spec.env | kind' seq

    echo '... Ensuring resource requests and limits are declared.'
    yq_ensure "$fname" '.spec.resources | kind' map
    yq_ensure "$fname" '.spec.resources | length' 2
    yq_ensure "$fname" '.spec.resources.requests | kind' map
    yq_ensure "$fname" '.spec.resources.limits | kind' map

    echo '... Ensuring a correct team ID is declared.'
    yq_ensure "$fname" '.spec.teamId' swpt

    echo '... Ensuring database users are correctly declared.'
    yq_ensure "$fname" '.spec.users | kind' map
    yq_ensure "$fname" '.spec.users | length' 1
    yq_ensure "$fname" '.spec.users.db_owner | kind' seq
    yq_ensure "$fname" '.spec.users.db_owner | length' 0

    echo '... Ensuring databases are correctly declared.'
    yq_ensure "$fname" '.spec.databases | kind' map
    yq_ensure "$fname" '.spec.databases | length' 1
    yq_ensure "$fname" '.spec.databases.db' db_owner
}

function ensure_successful_shard_kustomization_build {
    if ! kustomize build --output=/dev/null --load-restrictor=LoadRestrictionsNone "$DIR"; then
        echo
        echo "ERROR: Can not build shard's resources from the shard's Kustomization file."
        exit 1
    fi
}

function ensure_no_split_in_progress {
    fname="$DIR/kustomization.unsplit"
    echo "Checking $fname"
    if [[ -e "$fname" ]]; then
        echo
        echo "ERROR: A split is already in progress for \"$SHARD_BASENAME\"."
        exit 1
    fi
}

function ensure_no_existing_children_shards {
    for shard_suffix in "$SHARD0_SUFFIX" "$SHARD1_SUFFIX"
    do
        child_dir="$DIR/../$SHARDS_PREFIX$shard_suffix"
        echo "Checking ${child_dir}"
        if [[ -e "$child_dir" ]]; then
            echo
            echo "ERROR: A child-shard already exists: $SHARDS_PREFIX$shard_suffix"
            exit 1
        fi
    done
}

find_script_dir || exit 3

export BASE_DIR='../../../../base/swpt-accounts/shard/'
export SHARD_BASENAME=$(basename "$DIR")
export SHARD_SUFFIX=$(echo "$SHARD_BASENAME" | sed -nE 's/^.*(\-[01]+)$/\1/p')
export SHARD_ROUTING_KEY=$(echo "$SHARD_SUFFIX" | sed 's/^-//; s/./&./g; s/$/#/')
export SHARDS_PREFIX=$(echo "$SHARD_BASENAME" | sed -nE "s/^(.*)${SHARD_SUFFIX}$/\1/p")
export SHARD0_SUFFIX="$(echo "$SHARD_SUFFIX" | sed 's/^$/-/')0"
export SHARD1_SUFFIX="$(echo "$SHARD_SUFFIX" | sed 's/^$/-/')1"
export SHARD0_ROUTING_KEY=$(echo "$SHARD0_SUFFIX" | sed 's/^-//; s/./&./g; s/$/#/')
export SHARD1_ROUTING_KEY=$(echo "$SHARD1_SUFFIX" | sed 's/^-//; s/./&./g; s/$/#/')

validate_shard_kustomization_file
validate_shard_postgres_cluster
ensure_successful_shard_kustomization_build
ensure_no_existing_children_shards
ensure_no_split_in_progress

if [[ ${1:-} == "--validate-only" ]]; then
    echo
    echo "\"$SHARD_BASENAME\" is valid and can be split."
    exit 0
fi

echo
echo "Splitting \"$SHARD_BASENAME\":"

echo "... Creating $DIR/kustomization.unsplit"
cp "$DIR/kustomization.yaml" "$DIR/kustomization.unsplit"

for shard_suffix in "$SHARD0_SUFFIX" "$SHARD1_SUFFIX"
do
    shard_name=$SHARDS_PREFIX$shard_suffix
    child_dir="$DIR/../$shard_name"
    echo "... Creating ${child_dir}/"
    cp -r "$DIR" "${child_dir}"
    rm "${child_dir}/kustomization.unsplit"
    yq -i '.replicas[] |= (.count = 0)' "${child_dir}/kustomization.yaml"
done
